name: action pr approve template

on:
  workflow_call:
            
  workflow_dispatch:
    inputs:
      PR_number:
        description: 'Pull request number'
        required: true      
  
  pull_request:

    branches:
      - main
    types: [opened, reopened]
    
jobs:
  init: 
    name: Init process
    env:
      TECH_USER_SECRET: ${{ secrets.TECH_USER_SECRET }}
      TECH_USER: ${{ vars.TECH_USER }}
      URL: 'https://github.com/bw0101'
      ENVIRONMENT: 'dev'
      PR_number: ${{ github.event.inputs.PR_number }}
    runs-on: ubuntu-latest
    steps:
      - name: Add inputs to Summary
        run: |
          echo "#### env: "
          echo "| Name          | Value | " 
          echo "| _____________ | _____ | "
          echo "| PR_REPO       | ${{ inputs.PR_REPO }}    | "
          echo "| Tech user sec | $TECH_USER_SECRET | "
          echo "| Tech user     | $TECH_USER | "    
          echo "| Tech user var | ${{ vars.TECH_USER }} | " 
          echo "| URL           | $URL | " 
          echo "| ENVIRONMENT   | $ENVIRONMENT | " 
          git --version
          echo " _________________________"

  auto-approve:
    name: Auto approve of PR 
    if: github.event_name == 'pull_request' && contains( 'bw0101, $TECH_USER', github.actor )
    runs-on: ubuntu-latest
    needs: init
    environment:
      name: $ENVIRONMENT
      url: $URL
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      TECH_USER_SECRET: ${{ secrets.TECH_USER_SECRET }}

    permissions:
      pull-requests: write

    steps:         
      - name: PR approve
        if: ${{ success() }}
        uses: hmarr/auto-approve-action@v4
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          
    # ======================================================
    # When we're done, we need to update the PR one more time
    # with the results of the apply.
    # ======================================================      
      - name: Update status
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Pull-request processed
            > PR #${{ github.event.inputs.PR_number }} has been processed
            
            URL: http://${{ steps.apply_output.outputs.stdout }}`;
  
            github.rest.issues.createComment({
              issue_number: $PR_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
    
    
