name: approve PRs 21

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  checks: write
  pull-requests: write
  actions: read
  contents: read

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  check-todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name : Notes
        run: |
          echo 1. Info:
          echo The tech user is: ${{ secrets.TECH_USER }}
    
  notes-todos:
    runs-on: ubuntu-latest
    steps:
      - name : Notes
        run: |
          echo 1. Add further steps ,
          echo 2. Test, approve and merge your.
          echo 3. Go to 1. 

  autom-approve-pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Approve a PR if not already approved
        run: |
          gh pr checkout "$PR_NUMBER" # sets the upstream metadata for `gh pr status`
          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
          then gh pr review --approve "$PR_NUMBER"
          else echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
          fi

  autom-merge-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Enable auto-merge
        run: | 
          echo Imlpement this ...
      #    gh pr merge --auto --merge "$PR_NUMBER"
