name: Auto approve

on:
  workflow_call:
    inputs:
      environment:
        description: 'environment'
        type: string
        required: false
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment'
        type: string
        required: false
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/*

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: contains('bw0101,anotherUser', github.actor)

    steps:
      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      - name: Auto approve
        if: ${{ success() }}
        uses: hmarr/auto-approve-action@v4
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
      - name: Notify              
        run: |
          echo 1. auto approve processed
          echo 2. "PR #${{ github.event.pull_request.number }} was auto-approved."
