name: Auto approve

on:
  workflow_call:
    inputs:
      environment:
  workflow_dispatch:
    inputs:
      environment:

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'bw0101'
    steps:
      - uses: hmarr/auto-approve-action@v4
