name: auto approve action

on:
  workflow_call:
    inputs:
      PR_REPO:
        type: string
        required: true
      PR_REF:
        type: string
        required: true
      environment:
        description: 'environment'
        type: string
        required: false
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment'
        type: string
        required: false
  pull_request:
    branches:
      - main
      - release/*
    types: [opened, synchronize, reopened]

jobs:
  init: 
    runs-on: ubuntu-latest
    steps:
      - name: Add inputs to Summary
        if: inputs.PR_REPO
        run: |
          {
            echo "#### Inputs "
            echo "| Arg          | Value | " 
            echo "| ____________ | _____ | "
            echo "| PR_REPO      | ${{ inputs.PR_REPO }} | "
            echo "| PR_REF       | ${{ inputs.PR_REF }} | "
          } >> $GITHUB_STEP_SUMMARY
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: contains('bw0101,anotherUser', github.actor)

    steps:         
      - name: Auto approve
        if: ${{ success() }}
        uses: hmarr/auto-approve-action@v4
        with:
          pull-request-number: ${{ github.event.pull_request.number }}

