name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check out
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Print message
        run: echo GitHub Actions is running

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 1. Add other actions to build,
          echo 2. test, and deploy your project.
